backend:
  name: github
  repo: siuhangw/JekyllNetifyCMS

media_folder: "images/uploads"

collections:
  - name: "website-settings"
    label: "Website Setting"
    files:
    - label: "Website settings"
      name: "site"
      file: "_data/site.yml"
      fields: 
        - label: "Tel"
          name: "tel"
          widgets: "string"